###
POST http://localhost:8080/users/auth/register
Content-Type: application/json

{
  "email": "edu.slhenrique@gmail.com",
  "password": "12345678",
  "username": "Eduardo Henrique",
  "role": "ADMIN"
}