spring.application.name=gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=health
spring.cloud.gateway.server.webflux.routes[0].uri=lb://health
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/health,/health/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/health/?(?<remaining>.*),/$\{remaining}

server.max-http-request-header-size=64KB
api.security.token.secret=${API_SECURITY_TOKEN_SECRET:local-dev-secret}

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=false
